#!/usr/bin/env bash
# Regenerates deploy/all-in-one.yaml from the final overlay (Part 3 + reaper).
# Run after changing any manifest, worker or reaper script.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
{
  echo "# GENERATED by deploy/render.sh from bonus-reaper/manifests; do not edit."
  echo "# Finished assignment: Redis + worker (Part 1), KEDA autoscaling (Part 2),"
  echo "# graceful-shutdown worker (Part 3) and the reaper CronJob (bonus)."
  echo "# Needs the 'ingest' namespace and the 'redis-auth' Secret, which"
  echo "# deploy/deploy.sh creates."
  kubectl kustomize --load-restrictor LoadRestrictionsNone "$ROOT/bonus-reaper/manifests"
} >"$ROOT/deploy/all-in-one.yaml"
echo "wrote deploy/all-in-one.yaml"
